spring.application.name=RemindMe

spring.datasource.url=jdbc:h2:file:./data/remindmedb
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# This silences the 'noise'
logging.level.root=WARN