spring.application.name=RemindMe

# changed it from creating a file, to keeping the information in memory for easier development. which is: spring.datasource.url=jdbc:h2:mem:testdb
# old,where it creates a file is: spring.datasource.url=jdbc:h2:file:./data/remindmedb
spring.datasource.url=jdbc:h2:file:./data/remindmedb
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# This silences the 'noise'
logging.level.root=WARN