spring.application.name=RemindMe

# H2 Database (file-based so data survives restarts)
spring.datasource.url=jdbc:h2:file:./data/remindmedb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update


spring.mail.host=smtp.gmail.com
spring.mail.port=587


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.encryption.key=RemindMe2024Secure

# This silences the 'noise'
logging.level.root=WARN
